# Generated by Django 4.2.5 on 2023-09-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
