# Generated by Django 4.2.5 on 2023-09-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_first_name_alter_users_second_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
