# Generated by Django 4.2.5 on 2023-09-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_doctors_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='department',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='hospital',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
